### ISSUE TITLE
Disappearing Nvidia drivers

### ISSUE THREAD

**Issue by burntex** [linuxmint/nvidia-prime-applet#7]
see: https://forums.linuxmint.com/viewtopic.php?f=59&t=341289

from above link I also posted the issue at https://github.com/tseliot/nvidia-prime/issues

**Comment by burntex** [comment]
still a problem after upgrading ubuntu-drivers-common from 1:0.8.4~0.20.04.2 to 1:0.8.6.4~0.20.04.1.
see above topics/links for latest status

**Comment by burntex** [comment]
OK I didn't realize there are 2 prime-supported files in Mint. One is in /usr/bin and the other is in /var/lib/ubuntu-drivers-common/.
The applet uses the file in /usr/bin and nvidia-prime (select) uses the one in  /var/lib/ubuntu-drivers-common
I would suggest a modification to the one in /usr/bin/ to address the problem when the applet checks to see if prime is supported.
Change 
```
if [ -e "/var/lib/ubuntu-drivers-common/requires_offloading" ]; then
    echo "Requires offloading" >> $LOG 2>&1
    echo "yes"
else
    echo "No offloading required. Abort" >> $LOG 2>&1
```
To
if [ -e "/var/lib/ubuntu-drivers-common/prime-supported" ]; then
    echo "Prime supported" >> $LOG 2>&1
    echo "yes"
else
    echo "Prime not supported. Abort" >> $LOG 2>&1

If you agree or sugggest something different  let me know and you or I can update the issue in
https://forums.linuxmint.com/viewtopic.php?f=59&t=341289

Thx

**Comment by pnsantos** [comment]
I just noticed this on Linux Mint  `20.1` - I looks like it either `ubuntu-drivers-common` or `nvidia-prime` changed which broke the way the applet would detect if PRIME was supported or not.

The current output of `/usr/lib/nvidia-prime-applet/nvidia-prime` is:
```
❯ /usr/lib/nvidia-prime-applet/nvidia-prime
Aborting: prime not supported - is this a prime laptop and do you have nvidia drivers installed?
```
At startup `/usr/lib/nvidia-prime-applet/nvidia-prime` does this:
```python
    output = get_output(["prime-supported"])
    if output != "yes":
        print("Aborting: prime not supported - is this a prime laptop and do you have nvidia drivers installed?")
        sys.exit(0)
```
and if one looks in `prime-supported` (which comes from `nvidia-prime` package):
```bash
if [ -e "/var/lib/ubuntu-drivers-common/requires_offloading" ]; then
    echo "Requires offloading" >> $LOG 2>&1
    echo "yes"
else
    echo "No offloading required. Abort" >> $LOG 2>&1
    exit 0
fi
``` 
however if I look in `/var/lib/ubuntu-drivers-common/` (which comes from `ubuntu-drivers-common` package) all there is is this:
```
❯ ll /var/lib/ubuntu-drivers-common/
total 12K
drwxr-xr-x  2 root 4.0K Jan 25 19:27 .
drwxr-xr-x 72 root 4.0K Nov  5 15:38 ..
-rw-r--r--  1 root   50 Feb  8 15:06 last_gfx_boot
```
If I comment the nvidia-prime-applet `if` check the applet started fine (only the X server settings fail to be displayed - see below)

Running `sudo prime-select query` shows:
```
❯ sudo prime-select query         
intel
```
which is correct (I'm running in powersave mode). 

Running `sudo /usr/bin/prime-supported` gives
```
❯ sudo /usr/bin/prime-supported
❯ cat /var/log/prime-supported.log
No offloading required. Abort
```
Not sure if this was like this before of it it changed though...

Technically speaking the drivers and card is working fine, I believe the issue here is just the way the applet is starting which seems to have been broken by either `nvidia-prime` or `ubuntu-drivers-common` packages in a recent update (not sure when exactly but it was working fine a few weeks ago). 

Whatever changed in those packages also seems to break `Nvidia X Server Settings` now you get this:
![nvidia](https://user-images.githubusercontent.com/630567/107256370-506a0800-6a31-11eb-8295-a964f8499340.png)

and in syslog this:
```
Feb  8 17:15:07 Y03602 nvidia-settings[18364]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb  8 17:15:07 Y03602 nvidia-settings[18364]: PRIME: No offloading required. Abort
Feb  8 17:15:07 Y03602 nvidia-settings[18364]: PRIME: is it supported? no
```

**Comment by firewiremb** [comment]
I have exactly the same problem since updating to Mint 20.1 with my Laptop https://termbin.com/z7ewh

Running `sudo prime-select nvidia` switches the active graphics card to nvidia. After that the prime applet shows up and Nvidia X Server Settings ist working again. But after switching back to intel and rebooting the Problem occurs again.

**Comment by sanjayakarunasena** [comment]
I also have the same problem. I think the issue is in the `prime-supported` script since in Intel (Power Saving) mode once the Laptop is restarted, the `/var/lib/ubuntu-drivers-common/requires_offloading` file goes away. There should be a more reliable mechanism to check whether Prime is supported or not. I modified the `prime-supported` script to check whether `/etc/prime-discrete` is available or not and it works (including NVIDIA Settings).

```
if [ -e "/etc/prime-discrete" ]; then
    echo "Prime supported" >> $LOG 2>&1
    echo "yes"
else
    echo "Prime not supported. Abort" >> $LOG 2>&1
    exit 0
fi
```

**Comment by genbushi** [comment]
Same behavior here on `20.1`. The modification mentioned by @sanjayakarunasena did resolve the issue for me as well for both allowing the applet to run, and allowing nvidia-settings to run again.

**Comment by bentaye** [comment]
@sanjayakarunasena ' s fix worked for me too. Linux `Mint 20.1`, kernel `5.4.0-67`

**Comment by sheturnedmeintoanewt** [comment]
I'm completely new to Linux Mint... running Lenovo Legion Y720 with 20.1 just installed, and I don't even know what this means but I see others reference it: Kernel: 5.4.0-73-generic
I've tried @sanjayakarunasena ' s fix, and I get the applet but not the nvidia-settings. I can change Prime profiles, but I have no access to the settings. 
I assumed that:

if [ -e "/etc/prime-discrete" ]; then
    echo "Prime supported" >> $LOG 2>&1
    echo "yes"
else
    echo "Prime not supported. Abort" >> $LOG 2>&1
    exit 0
fi

is supposed to replace:

if [ -e "/var/lib/ubuntu-drivers-common/requires_offloading" ]; then
    echo "Requires offloading" >> $LOG 2>&1
    echo "yes"
else
    echo "No offloading required. Abort" >> $LOG 2>&1
    exit 0
fi

Oh, and I've tried both of these drivers: 460.73.01-0ubuntu0.20.04.2 and 465.27-0ubuntu0.20.04.1
Suggestions?

**Comment by sheturnedmeintoanewt** [comment]
I'm not sure if this is helpful or significant, but... my prime-supported script ends like this:


LOG=/var/log/prime-supported.log

if [ -n "$1" ]; then
    LOG="$1"
fi

# Remove any previous logs
# as long as the log is an actual
# file. In some cases we may pass
# it /dev/stdout which is a link
if [ -f $LOG ]; then
    rm -f $LOG
fi

if [ -e "/etc/prime-discrete" ]; then
    echo "Prime supported" >> $LOG 2>&1
    echo "yes"
else
    echo "Prime not supported. Abort" >> $LOG 2>&1
    exit 0
fi

When I do nvidia-settings in terminal, I get this output:

scott@scott-Lenovo-Y720-15IKB:~$ nvidia-settings

ERROR: NVIDIA driver is not loaded


ERROR: Unable to load info from any available system


(nvidia-settings:2390): GLib-GObject-CRITICAL **: 17:02:28.570: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** Message: 17:02:28.572: PRIME: Prime supported
** Message: 17:02:28.572: PRIME: is it supported? yes
** Message: 17:02:28.598: PRIME: Usage: /usr/bin/prime-select nvidia|intel|on-demand|query
** Message: 17:02:28.598: PRIME: on-demand mode: "1"
** Message: 17:02:28.598: PRIME: is "on-demand" mode supported? yes

While the tray icon says that I'm in nvidia performance mode.

![image](https://user-images.githubusercontent.com/84252320/118562613-a0442380-b732-11eb-83f1-555e9e64473f.png)

**Comment by sheturnedmeintoanewt** [comment]
![image](https://user-images.githubusercontent.com/84252320/118567444-6cb9c700-b73b-11eb-85a2-0711108b0958.png)

**Comment by clefebvre** [comment]
`/etc/prime-discrete` exists even on non-prime GPU.

A better way to identify a hybrid system is by looking in `/var/lib/ubuntu-drivers-common/last_gfx_boot`. This file should contain two ID, one for Intel and one for NVIDIA.

**Comment by clefebvre** [comment]
I'll troubleshoot this tomorrow, identify who's maintaining what and where the regression comes from.

**Comment by sheturnedmeintoanewt** [comment]
Looking forward to any help on this. At this point, I've stopped trying.
Driver manager says that I have the 460 driver installed.
There is no applet in the system tray.
The Nvidia settings available through the main menu only shows prime profiles, but no settings.
"nvidia-settings" through the terminal spits out these:
![image](https://user-images.githubusercontent.com/84252320/119389763-aa65a500-bc91-11eb-92af-0174dd25397d.png)
So... I don't know what driver I'm actually using... or what's going on.

**Comment by sheturnedmeintoanewt** [comment]
I looked in /var/lib/ubuntu-drivers-common/last_gfx_boot and see the following:

8086:591b;0000:00:02:0;1
10de:1c20;0000:01:00:0;0

**Comment by clefebvre** [comment]
`/var/lib/ubuntu-drivers-common/last_gfx_boot` shows the GPUs and their PCI Vendor ID:

- `8086` for Intel
- `10de` for NVIDIA
- `1002` for AMD

We can use this to identify if more than 1 GPU is present and to make sure we're on a hybrid system.

**Comment by clefebvre** [comment]
The regression comes from ubuntu-drivers-common. I can reproduce it by upgrading it and without upgrading NVIDIA and nvidia-prime. After upgrade the `/var/lib/ubuntu-drivers-common/requires_offloading` file is no longer present in Intel mode. It was the presence of this file `prime-supported` was checking. 

@tseliot mentions `prime-supported` isn't supposed to be used so this probably isn't a regression on the Ubuntu side, it just affects us negatively because we relied on it.

`prime-select` is still functional but it only switches devices, it doesn't help us assess capabilities.

`/var/lib/ubuntu-drivers-common/last_gfx_boot` looks like a good candidate to assess capabilities to me though. We can read it and detect the following information:

- How many GPUs are present
- Whether or not we're on Intel+NVIDIA system
- Whether or not we're on an AMD+NVIDIA system (@mtwebster started work to support this case, apparently using `prime-select intel` switches to the integrated AMD GPU on these systems, and when the AMD chipset is used `prime-select query` reports intel).

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/nvidia-prime-applet/commit/6b7aaa1380a2045dfe844d9e5d4f736246eae97f

Michael introduced support for AMD in https://github.com/linuxmint/nvidia-prime-applet/commit/c7cb72f8874d9564770f49f896166479743624a4. This will be backported as well. It needs new translations so this will take a few days.

In the meantime here's a build with the fix included: 
[applet.zip](https://github.com/linuxmint/nvidia-prime-applet/files/6539298/applet.zip)

**Comment by sheturnedmeintoanewt** [comment]
Well, I'm lost. I followed the link, but have no idea what to do with the information. I don't see a package to download, and the software manager only gives me the option of 1.2.6

**Comment by clefebvre** [comment]
It's available in Mint 20 and 20.1. Here's a direct link http://packages.linuxmint.com/pool/main/n/nvidia-prime-applet/nvidia-prime-applet_1.2.7_all.deb

**Comment by sheturnedmeintoanewt** [comment]
Awesome... wonderful... thank a million!

**Comment by sheturnedmeintoanewt** [comment]
Well... here's where I am now. I don't know if you'll have the time, patience, or inclination to help, but here goes.
I ran the deb you posted, and got the applet but still no access to settings. So, I tried changing and then re-installing the nvidia drivers. That just made things worse, since after that that applet just produced a blank settings window.
So, I purged all things nvidia with this: sudo apt-get --purge remove '*nvidia*'  ... rebooted, reinstalled the driver and your fix, and no change.
So I purged nvidia again, but this time went to the mint software manager as well, and removed anything related to nvidia... Bumblebee, screen-resolution-extra, and a few others. Reboot, install 460 driver, reboot, install deb above through the software manager, reboot... and I'm now here:
![image](https://user-images.githubusercontent.com/84252320/119558462-0a7a4b00-bd67-11eb-93d8-7195096ab5b9.png)

**Comment by clefebvre** [comment]
You can use `prime-select query` to double-check which GPU is supposed to be active, and `inxi -Gxx` to see which renderer is actually in use.

I didn't look into 460 yet (I was still using 455 at the time) but for me in Intel mode I wouldn't get much in the NVIDIA settings. They would only appear when I was in performance mode (NVIDIA). That's by design on NVIDIA's side.

I also noticed a few times that prime failed to switch to NVIDIA. Even though `prime-select query` reported `nvidia`, the renderer was still Intel (MESA). When that happened I'd usually reboot.

**Comment by monsta** [comment]
@sheturnedmeintoanewt: regarding that empty window - maybe you didn't apply the changes to `prime-supported` after you reinstalled all nvidia stuff?
